# Generated by Django 4.0.3 on 2022-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('comments', models.CharField(max_length=255)),
                ('availability', models.BooleanField(default=True)),
                ('category', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('unit', models.CharField(max_length=24)),
                ('sale', models.BooleanField(default=False)),
                ('stock', models.IntegerField()),
                ('sold', models.IntegerField()),
            ],
        ),
    ]
